#!/bin/bash -l
#参数名称：appPath 变量名称：$appPath 应用路径
#SBATCH --job-name="sk_zh"
#SBATCH --partition=RGZN2
#SBATCH --qos=normal
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks-per-core=1
#SBATCH --output=/home/y20212721/Youngtop/code_ja_relation/shell1/job.%j.out
#SBATCH --error=/home/y20212721/Youngtop/code_ja_relation/shell1/joberror.%j.out
#SBATCH --gpus=1

source activate tensorflow

module add cuda/10.1

python main.py
